version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - node-mongo-data:/data/db

  server:
    depends_on:
      - mongodb
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5000:5000"
    environment:
      - NODE_PORT=5000
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

  weather-forecast-web:
    depends_on:
      - server
    build: 
      context: ./weather-forecast-web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"

  weather-forecast-app:
    depends_on:
      - server
    build: 
      context: ./weather_forecast_app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - "8080:8080"

volumes:
  node-mongo-data:

      
